flask:
   build: ./src/
   command: python /src/app.py
   ports:
         - "5000:5000"
   volumes:
         - ./src:/src
         - /etc/localtime:/etc/localtime:ro
   environment:
         - GATEWAY=http://192.168.1.3:5001
         
